# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='on',
            field=models.BooleanField(default=True),
        ),
    ]
