# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointement_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointement_time',
            field=models.TimeField(null=True),
        ),
    ]
