# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamas', '0002_appointment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='on',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
