# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pamas', '0002_auto_20180325_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointement_date',
            new_name='appointment_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointement_time',
            new_name='appointment_time',
        ),
    ]
